# 1. node 설치
    # FROM : 기본 이미지
    # RUN : 쉘 명령어 실행
FROM ubuntu:22.04
RUN apt-get update                                  
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

# 1번의 5개의 명령어가 node를 보유한 ubuntu 이미지로 대체 하면서 최적화 가능
# FROM node:16


# 2. 소스 복사, 모든 파일, 디렉토리를 경로(/usr/src/app)에 복사
COPY . /usr/src/app


# 3. Nodejs 패키지 설치, (해당 경로로 이동)
WORKDIR /usr/src/app 
RUN npm install


# 4. WEB 서버 실행 (Listen 포트 정의)
    # EXPOSE : 오픈되는 포트 정보
    # CMD : 컨테이너 기본 실행 명령어
EXPOSE 3000
CMD node app.js